# Generated by Django 4.1.2 on 2022-11-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='gallery')),
            ],
        ),
        migrations.AlterField(
            model_name='visitorsmodel',
            name='image',
            field=models.FileField(upload_to='gallery'),
        ),
    ]
