# Generated by Django 4.1.2 on 2022-11-23 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0002_ourteammodel_alter_visitorsmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age_old_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('age_old_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('age_old_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.FileField(upload_to='gallery')),
                ('species', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('B', 'boy'), ('G', 'girl')], default='B', max_length=1)),
            ],
        ),
    ]
