# Generated by Django 4.1.2 on 2022-11-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0003_petsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsmodel',
            name='status',
            field=models.CharField(choices=[('B', 'boy'), ('G', 'girl')], default='H', max_length=1),
        ),
    ]
